# Form implementation generated from reading ui file 'ui/connect_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectScreen(object):
    def setupUi(self, ConnectScreen):
        ConnectScreen.setObjectName("ConnectScreen")
        ConnectScreen.setEnabled(False)
        ConnectScreen.resize(544, 333)
        self.centralwidget = QtWidgets.QWidget(ConnectScreen)
        self.centralwidget.setObjectName("centralwidget")
        self.name_input = QtWidgets.QTextEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(180, 70, 261, 31))
        self.name_input.setObjectName("name_input")
        self.host_input = QtWidgets.QTextEdit(self.centralwidget)
        self.host_input.setGeometry(QtCore.QRect(180, 120, 261, 31))
        self.host_input.setObjectName("host_input")
        self.port_input = QtWidgets.QTextEdit(self.centralwidget)
        self.port_input.setGeometry(QtCore.QRect(180, 170, 261, 31))
        self.port_input.setObjectName("port_input")
        self.token_input = QtWidgets.QTextEdit(self.centralwidget)
        self.token_input.setGeometry(QtCore.QRect(180, 220, 261, 31))
        self.token_input.setObjectName("token_input")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 270, 261, 41))
        self.pushButton.setObjectName("pushButton")
        self.Name = QtWidgets.QLabel(self.centralwidget)
        self.Name.setGeometry(QtCore.QRect(120, 80, 58, 16))
        self.Name.setObjectName("Name")
        self.Host = QtWidgets.QLabel(self.centralwidget)
        self.Host.setGeometry(QtCore.QRect(120, 130, 58, 16))
        self.Host.setObjectName("Host")
        self.Port = QtWidgets.QLabel(self.centralwidget)
        self.Port.setGeometry(QtCore.QRect(120, 180, 58, 16))
        self.Port.setObjectName("Port")
        self.Token = QtWidgets.QLabel(self.centralwidget)
        self.Token.setGeometry(QtCore.QRect(120, 230, 58, 16))
        self.Token.setObjectName("Token")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 20, 58, 16))
        self.label.setObjectName("label")
        ConnectScreen.setCentralWidget(self.centralwidget)

        self.retranslateUi(ConnectScreen)
        QtCore.QMetaObject.connectSlotsByName(ConnectScreen)

    def retranslateUi(self, ConnectScreen):
        _translate = QtCore.QCoreApplication.translate
        ConnectScreen.setWindowTitle(_translate("ConnectScreen", "MainWindow"))
        self.pushButton.setText(_translate("ConnectScreen", "Connect"))
        self.Name.setText(_translate("ConnectScreen", "Name"))
        self.Host.setText(_translate("ConnectScreen", "Host"))
        self.Port.setText(_translate("ConnectScreen", "Port"))
        self.Token.setText(_translate("ConnectScreen", "Token"))
        self.label.setText(_translate("ConnectScreen", "Connect"))
