# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: implantpb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fimplantpb.proto\x12\timplantpb\"s\n\x0cRegistration\x12\n\n\x02ip\x18\x01 \x01(\t\x12\n\n\x02os\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\r\x12\x1d\n\x04user\x18\x04 \x01(\x0b\x32\x0f.implantpb.User\x12\x1f\n\x06groups\x18\x05 \x03(\x0b\x32\x0f.implantpb.User\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'implantpb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REGISTRATION._serialized_start=30
  _REGISTRATION._serialized_end=145
  _USER._serialized_start=147
  _USER._serialized_end=179
# @@protoc_insertion_point(module_scope)
