# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: implantpb.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0fimplantpb.proto\x12\timplantpb\"\xd2\x01\n\x07Message\x12\x34\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x1e.implantpb.Message.MessageType\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\"\x82\x01\n\x0bMessageType\x12\t\n\x05\x45rror\x10\x00\x12\x10\n\x0cRegistration\x10\x01\x12\x1c\n\x18RegistrationConfirmation\x10\x02\x12\t\n\x05OsCmd\x10\x03\x12\x0f\n\x0bOsCmdOutput\x10\x04\x12\x0c\n\x08\x46ileXfer\x10\x05\x12\x0e\n\nFilePacket\x10\x06\"\x93\x01\n\x05\x45rror\x12.\n\nerror_type\x18\x01 \x01(\x0e\x32\x1a.implantpb.Error.ErrorType\x12\x0f\n\x07message\x18\x02 \x01(\t\"I\n\tErrorType\x12\x11\n\rMessageDecode\x10\x00\x12\x10\n\x0cRegistration\x10\x01\x12\t\n\x05OsCmd\x10\x02\x12\x0c\n\x08\x46ileXfer\x10\x03\"\xb1\x01\n\x0cRegistration\x12\x0c\n\x04\x61\x64\x64r\x18\x01 \x01(\t\x12\n\n\x02os\x18\x02 \x01(\t\x12\x0b\n\x03pid\x18\x03 \x01(\r\x12*\n\x04user\x18\x04 \x01(\x0b\x32\x1c.implantpb.Registration.User\x12,\n\x06groups\x18\x05 \x03(\x0b\x32\x1c.implantpb.Registration.User\x1a \n\x04User\x12\n\n\x02id\x18\x01 \x01(\r\x12\x0c\n\x04name\x18\x02 \x01(\t\"&\n\x18RegistrationConfirmation\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x05OsCmd\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\"G\n\x0bOsCmdOutput\x12\x0e\n\x04\x63ode\x18\x01 \x01(\x05H\x00\x12\x0e\n\x06stdout\x18\x02 \x01(\x0c\x12\x0e\n\x06stderr\x18\x03 \x01(\x0c\x42\x08\n\x06status\".\n\x08\x46ileXfer\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x63hecksum\x18\x02 \x01(\x0c\"\x1a\n\nFilePacket\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'implantpb_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=31
  _MESSAGE._serialized_end=241
  _MESSAGE_MESSAGETYPE._serialized_start=111
  _MESSAGE_MESSAGETYPE._serialized_end=241
  _ERROR._serialized_start=244
  _ERROR._serialized_end=391
  _ERROR_ERRORTYPE._serialized_start=318
  _ERROR_ERRORTYPE._serialized_end=391
  _REGISTRATION._serialized_start=394
  _REGISTRATION._serialized_end=571
  _REGISTRATION_USER._serialized_start=539
  _REGISTRATION_USER._serialized_end=571
  _REGISTRATIONCONFIRMATION._serialized_start=573
  _REGISTRATIONCONFIRMATION._serialized_end=611
  _OSCMD._serialized_start=613
  _OSCMD._serialized_end=633
  _OSCMDOUTPUT._serialized_start=635
  _OSCMDOUTPUT._serialized_end=706
  _FILEXFER._serialized_start=708
  _FILEXFER._serialized_end=754
  _FILEPACKET._serialized_start=756
  _FILEPACKET._serialized_end=782
# @@protoc_insertion_point(module_scope)
