# Form implementation generated from reading ui file 'resources/ui/event_viewer.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EventViewer(object):
    def setupUi(self, EventViewer):
        EventViewer.setObjectName("EventViewer")
        EventViewer.resize(632, 422)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        EventViewer.setFont(font)
        EventViewer.setStyleSheet("background-color:#171724")
        self.gridLayout = QtWidgets.QGridLayout(EventViewer)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(EventViewer)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)

        self.retranslateUi(EventViewer)
        QtCore.QMetaObject.connectSlotsByName(EventViewer)

    def retranslateUi(self, EventViewer):
        _translate = QtCore.QCoreApplication.translate
        EventViewer.setWindowTitle(_translate("EventViewer", "Form"))
