# Form implementation generated from reading ui file 'client/gui/resources/ui/generate_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_GenerateScreen(object):
    def setupUi(self, GenerateScreen):
        GenerateScreen.setObjectName("GenerateScreen")
        GenerateScreen.resize(600, 350)
        GenerateScreen.setMinimumSize(QtCore.QSize(600, 350))
        GenerateScreen.setMaximumSize(QtCore.QSize(600, 350))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        GenerateScreen.setFont(font)
        GenerateScreen.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(GenerateScreen)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(parent=GenerateScreen)
        self.widget.setObjectName("widget")
        self.Host = QtWidgets.QTextEdit(parent=self.widget)
        self.Host.setGeometry(QtCore.QRect(150, 70, 341, 41))
        self.Host.setObjectName("Host")
        self.Port = QtWidgets.QTextEdit(parent=self.widget)
        self.Port.setGeometry(QtCore.QRect(150, 130, 341, 41))
        self.Port.setObjectName("Port")
        self.genBtn = QtWidgets.QPushButton(parent=self.widget)
        self.genBtn.setGeometry(QtCore.QRect(200, 250, 201, 51))
        self.genBtn.setObjectName("genBtn")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setGeometry(QtCore.QRect(70, 140, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setGeometry(QtCore.QRect(70, 190, 58, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(70, 80, 58, 16))
        self.label_3.setObjectName("label_3")
        self.windowsBtn = QtWidgets.QRadioButton(parent=self.widget)
        self.windowsBtn.setGeometry(QtCore.QRect(320, 190, 121, 20))
        self.windowsBtn.setObjectName("windowsBtn")
        self.linuxBtn = QtWidgets.QRadioButton(parent=self.widget)
        self.linuxBtn.setGeometry(QtCore.QRect(190, 190, 121, 20))
        self.linuxBtn.setObjectName("linuxBtn")
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(GenerateScreen)
        QtCore.QMetaObject.connectSlotsByName(GenerateScreen)

    def retranslateUi(self, GenerateScreen):
        _translate = QtCore.QCoreApplication.translate
        GenerateScreen.setWindowTitle(_translate("GenerateScreen", "Generate"))
        self.genBtn.setText(_translate("GenerateScreen", "Generate"))
        self.label.setText(_translate("GenerateScreen", "Port"))
        self.label_2.setText(_translate("GenerateScreen", "OS"))
        self.label_3.setText(_translate("GenerateScreen", "Host"))
        self.windowsBtn.setText(_translate("GenerateScreen", "Windows"))
        self.linuxBtn.setText(_translate("GenerateScreen", "Linux"))
