# Form implementation generated from reading ui file 'gui/resources/ui/connect_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectScreen(object):
    def setupUi(self, ConnectScreen):
        ConnectScreen.setObjectName("ConnectScreen")
        ConnectScreen.resize(600, 350)
        ConnectScreen.setMinimumSize(QtCore.QSize(600, 350))
        ConnectScreen.setMaximumSize(QtCore.QSize(600, 350))
        font = QtGui.QFont()
        font.setFamily("Monaco")
        ConnectScreen.setFont(font)
        ConnectScreen.setStyleSheet("")
        self.horizontalLayout = QtWidgets.QHBoxLayout(ConnectScreen)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(ConnectScreen)
        self.widget.setObjectName("widget")
        self.Host = QtWidgets.QTextEdit(self.widget)
        self.Host.setGeometry(QtCore.QRect(150, 80, 341, 41))
        self.Host.setObjectName("Host")
        self.Port = QtWidgets.QTextEdit(self.widget)
        self.Port.setGeometry(QtCore.QRect(150, 150, 341, 41))
        self.Port.setObjectName("Port")
        self.connectButton = QtWidgets.QPushButton(self.widget)
        self.connectButton.setGeometry(QtCore.QRect(200, 220, 201, 51))
        self.connectButton.setObjectName("connectButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(70, 90, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(70, 160, 58, 16))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.widget)

        self.retranslateUi(ConnectScreen)
        QtCore.QMetaObject.connectSlotsByName(ConnectScreen)

    def retranslateUi(self, ConnectScreen):
        _translate = QtCore.QCoreApplication.translate
        ConnectScreen.setWindowTitle(_translate("ConnectScreen", "Connect"))
        self.connectButton.setText(_translate("ConnectScreen", "Connect"))
        self.label.setText(_translate("ConnectScreen", "Host"))
        self.label_2.setText(_translate("ConnectScreen", "Port"))
