# Form implementation generated from reading ui file 'resources/ui/connect_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ConnectScreen(object):
    def setupUi(self, ConnectScreen):
        ConnectScreen.setObjectName("ConnectScreen")
        ConnectScreen.resize(661, 422)
        font = QtGui.QFont()
        font.setFamily("Monaco")
        ConnectScreen.setFont(font)
        ConnectScreen.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(ConnectScreen)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget = QtWidgets.QWidget(ConnectScreen)
        self.widget.setObjectName("widget")
        self.Host = QtWidgets.QTextEdit(self.widget)
        self.Host.setGeometry(QtCore.QRect(170, 90, 341, 41))
        self.Host.setObjectName("Host")
        self.Name = QtWidgets.QTextEdit(self.widget)
        self.Name.setGeometry(QtCore.QRect(170, 160, 341, 41))
        self.Name.setObjectName("Name")
        self.Port = QtWidgets.QTextEdit(self.widget)
        self.Port.setGeometry(QtCore.QRect(170, 230, 341, 41))
        self.Port.setObjectName("Port")
        self.Token = QtWidgets.QTextEdit(self.widget)
        self.Token.setGeometry(QtCore.QRect(170, 300, 341, 41))
        self.Token.setMinimumSize(QtCore.QSize(1, 0))
        self.Token.setObjectName("Token")
        self.connectButton = QtWidgets.QPushButton(self.widget)
        self.connectButton.setGeometry(QtCore.QRect(240, 360, 201, 51))
        self.connectButton.setObjectName("connectButton")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(80, 100, 58, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(80, 240, 58, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(80, 310, 58, 16))
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(80, 170, 58, 16))
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)

        self.retranslateUi(ConnectScreen)
        QtCore.QMetaObject.connectSlotsByName(ConnectScreen)

    def retranslateUi(self, ConnectScreen):
        _translate = QtCore.QCoreApplication.translate
        ConnectScreen.setWindowTitle(_translate("ConnectScreen", "Connect"))
        self.connectButton.setText(_translate("ConnectScreen", "Connect"))
        self.label.setText(_translate("ConnectScreen", "Host"))
        self.label_2.setText(_translate("ConnectScreen", "Port"))
        self.label_4.setText(_translate("ConnectScreen", "Token"))
        self.label_3.setText(_translate("ConnectScreen", "Name"))
