# Form implementation generated from reading ui file 'ui/main_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(717, 572)
        font = QtGui.QFont()
        font.setFamily("Academy Engraved LET")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QWidget{\n"
"background-color:#16161D\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 717, 24))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuAvocado = QtWidgets.QMenu(self.menubar)
        self.menuAvocado.setObjectName("menuAvocado")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuAttack = QtWidgets.QMenu(self.menubar)
        self.menuAttack.setObjectName("menuAttack")
        self.menuScripts = QtWidgets.QMenu(self.menubar)
        self.menuScripts.setObjectName("menuScripts")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setCheckable(False)
        self.actionAbout.setChecked(False)
        self.actionAbout.setObjectName("actionAbout")
        self.actionPreferences = QtGui.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionQuit_Avocado = QtGui.QAction(MainWindow)
        self.actionQuit_Avocado.setObjectName("actionQuit_Avocado")
        self.actionPlaceholder = QtGui.QAction(MainWindow)
        self.actionPlaceholder.setObjectName("actionPlaceholder")
        self.actionPlaceholder_2 = QtGui.QAction(MainWindow)
        self.actionPlaceholder_2.setObjectName("actionPlaceholder_2")
        self.actionPlaceholder_3 = QtGui.QAction(MainWindow)
        self.actionPlaceholder_3.setObjectName("actionPlaceholder_3")
        self.actionPlaceholder_4 = QtGui.QAction(MainWindow)
        self.actionPlaceholder_4.setObjectName("actionPlaceholder_4")
        self.actionPlaceholder_5 = QtGui.QAction(MainWindow)
        self.actionPlaceholder_5.setObjectName("actionPlaceholder_5")
        self.menuAvocado.addAction(self.actionAbout)
        self.menuAvocado.addAction(self.actionPlaceholder_2)
        self.menuAvocado.addSeparator()
        self.menuAvocado.addAction(self.actionPreferences)
        self.menuAvocado.addSeparator()
        self.menuAvocado.addAction(self.actionQuit_Avocado)
        self.menuView.addAction(self.actionPlaceholder)
        self.menuAttack.addAction(self.actionPlaceholder_3)
        self.menuScripts.addAction(self.actionPlaceholder_4)
        self.menuHelp.addAction(self.actionPlaceholder_5)
        self.menubar.addAction(self.menuAvocado.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuAttack.menuAction())
        self.menubar.addAction(self.menuScripts.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Avocado 🥑"))
        self.menuAvocado.setTitle(_translate("MainWindow", "Avocado"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuAttack.setTitle(_translate("MainWindow", "Attack"))
        self.menuScripts.setTitle(_translate("MainWindow", "Scripts"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About Avocado"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences..."))
        self.actionQuit_Avocado.setText(_translate("MainWindow", "Quit Avocado"))
        self.actionPlaceholder.setText(_translate("MainWindow", "Placeholder"))
        self.actionPlaceholder_2.setText(_translate("MainWindow", "Placeholder"))
        self.actionPlaceholder_3.setText(_translate("MainWindow", "Placeholder"))
        self.actionPlaceholder_4.setText(_translate("MainWindow", "Placeholder"))
        self.actionPlaceholder_5.setText(_translate("MainWindow", "Placeholder"))
